Rename the notify rule to notifyExpr to avoid conflicts in generated Java
ANTLR4 will generate a `notify` method which causes a compile time error:

Otto.java:982: error: notify() in StageStatementsContext cannot override notify() in Object
                public NotifyContext notify() {
                                     ^
  overridden method is final
Otto.java:1831: error: notify() in Otto cannot override notify() in Object
        public final NotifyContext notify() throws RecognitionException {
                                   ^
  overridden method is final
2 errors

While we're not focusing on Java right now, ensuring some compilation works
properly is not a bad thing