Propagate a bus reference into the Connection and attempt to use it (failing)
This is currently failing due to some issues with lifetimes:

error: cannot infer an appropriate lifetime
   --> eventbus/src/server/main.rs:207:22
    |
207 |     async fn runloop(&mut self) {
    |                      ^^^^^^^^^ ...but this borrow...
...
213 |         let writer = tokio::task::spawn(async {
    |                      ------------------ this return type evaluates to the `'static` lifetime...
    |
note: ...can't outlive the lifetime `'_` as defined on the method body at 207:22
   --> eventbus/src/server/main.rs:207:22
    |
207 |     async fn runloop(&mut self) {
    |                      ^
help: you can add a constraint to the return type to make it last less than `'static` and match the lifetime `'_` as defined on the method body at 207:22
    |
213 |         let writer = tokio::task::spawn + '_(async {
    |                      ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Unfortunately the proposed syntax does not work properly, so I will have to wait
for a wireless connection in order to determine the right syntax here